[package]
name = "miniyear/camerashaker"
description = "Camera shake effects for Roblox games"
version = "1.0.2"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]